# 1.3. Introducing the multidimensional array in NumPy for fast array computations

In [1]:
import random
import numpy as np

In [2]:
n = 1000000
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]

In [3]:
x[:3], y[:3]

([0.9327910624021601, 0.46375406223323357, 0.40898069860113506],
 [0.476706345310703, 0.9659674789204357, 0.11282598516914266])

In [4]:
z = [x[i] + y[i] for i in range(n)]
z[:3]

[1.409497407712863, 1.4297215411536692, 0.5218066837702777]

In [5]:
%timeit [x[i] + y[i] for i in range(n)]

132 ms ± 1.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
xa = np.array(x)
ya = np.array(y)

In [7]:
xa[:3]

array([0.93279106, 0.46375406, 0.4089807 ])

In [8]:
za = xa + ya
za[:3]

array([1.40949741, 1.42972154, 0.52180668])

In [9]:
%timeit xa + ya

5.09 ms ± 77.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
%timeit sum(x)  # pure Python

6.3 ms ± 318 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%timeit np.sum(xa)  # NumPy

1.22 ms ± 216 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [12]:
d = [abs(x[i] - y[j])
     for i in range(1000)
     for j in range(1000)]

In [13]:
d[:3]

[0.45608471709145715, 0.03317641651827552, 0.8199650772330175]

In [14]:
da = np.abs(xa[:1000, np.newaxis] - ya[:1000])

In [15]:
da

array([[0.45608472, 0.03317642, 0.81996508, ..., 0.24401727, 0.04290477,
        0.82840349],
       [0.01295228, 0.50221342, 0.35092808, ..., 0.22501973, 0.51194177,
        0.35936649],
       [0.06772565, 0.55698678, 0.29615471, ..., 0.27979309, 0.56671514,
        0.30459312],
       ...,
       [0.09856833, 0.3906928 , 0.46244869, ..., 0.11349911, 0.40042116,
        0.4708871 ],
       [0.48386813, 0.00539301, 0.84774849, ..., 0.27180068, 0.01512137,
        0.85618689],
       [0.40402722, 0.08523392, 0.76790758, ..., 0.19195977, 0.09496227,
        0.77634598]])

In [16]:
%timeit np.abs(xa[:1000, np.newaxis] - ya[:1000])

9.01 ms ± 327 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [17]:
%timeit [abs(x[i] - y[j]) \
         for i in range(1000) \
         for j in range(1000)]

185 ms ± 14.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
